# Generated by Django 4.0.2 on 2022-02-19 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodtruckfinderapi', '0002_day_foodtype_neighborhood_truck_usertruckreview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='days_with_trucks',
            field=models.ManyToManyField(related_name='neighborhoods', through='foodtruckfinderapi.TruckLocation', to='foodtruckfinderapi.Day'),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='map_img_src',
            field=models.ImageField(null=True, upload_to='neighborhoods'),
        ),
        migrations.AddField(
            model_name='truck',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_trucks', through='foodtruckfinderapi.UserTruckFavorite', to='foodtruckfinderapi.UserAccount'),
        ),
        migrations.AddField(
            model_name='truck',
            name='owners',
            field=models.ManyToManyField(related_name='trucks_owned', through='foodtruckfinderapi.TruckOwner', to='foodtruckfinderapi.UserAccount'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user_favorites',
            field=models.ManyToManyField(through='foodtruckfinderapi.UserTruckFavorite', to='foodtruckfinderapi.Truck'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='profile_img_src',
            field=models.ImageField(null=True, upload_to='trucks'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
